# Generated by Django 2.1.1 on 2019-03-28 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('e164', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('portedin', 'Ported In'), ('portedout', 'Ported Out'), ('portingin', 'Porting In'), ('portingout', 'Porting Out'), ('disabled', 'Disabled')], default='portedin', max_length=10)),
            ],
            options={
                'db_table': 'number',
            },
        ),
    ]
