# Generated by Django 2.1.1 on 2019-03-28 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('number', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBase',
            fields=[
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('canceled', 'canceled'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Account')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderBase')),
            ],
            options={
                'db_table': 'order_comment',
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('kind', models.TextField()),
                ('file_name', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderBase')),
            ],
            options={
                'db_table': 'order_file',
            },
        ),
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='number.Number')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderBase')),
            ],
            options={
                'db_table': 'order_number',
            },
        ),
        migrations.CreateModel(
            name='OrderPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(max_length=15, unique=True)),
                ('port_type', models.CharField(choices=[('partial', 'partial'), ('full', 'full')], default='partial', max_length=50)),
                ('ddd', models.DateTimeField(default=django.utils.timezone.now)),
                ('btn', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('authorizer', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('foc', 'foc'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderBase')),
            ],
            options={
                'db_table': 'order_port',
            },
        ),
    ]
