# Generated by Django 2.1.1 on 2019-03-28 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'account_number',
            },
        ),
        migrations.CreateModel(
            name='AccountServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Account')),
            ],
            options={
                'db_table': 'account_server',
            },
        ),
        migrations.CreateModel(
            name='E911',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('zipcode2', models.CharField(blank=True, max_length=5, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accountnumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.AccountNumber')),
            ],
            options={
                'db_table': 'account_number_e911',
            },
        ),
        migrations.CreateModel(
            name='Lidb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('residential', 'Residential'), ('business', 'Business')], default='business', max_length=12)),
                ('name', models.CharField(max_length=15)),
                ('accountnumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.AccountNumber')),
            ],
            options={
                'db_table': 'account_number_lidb',
            },
        ),
    ]
