# Generated by Django 2.1.1 on 2019-03-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('number', '0001_initial'),
        ('account', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountserver',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Server'),
        ),
        migrations.AddField(
            model_name='accountnumber',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Account'),
        ),
        migrations.AddField(
            model_name='accountnumber',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='number.Number'),
        ),
        migrations.AlterUniqueTogether(
            name='accountserver',
            unique_together={('account', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='accountnumber',
            unique_together={('account', 'number')},
        ),
    ]
